import Head from 'next/head';
import styled from 'styled-components';
import About from '../components/About';
import Contact from '../components/Contact';
import Hero from '../components/Hero';
import Portfolio from '../components/Portfolio';
import SideBar from '../components/Sidebar';

const Layout = styled.div`
  margin-left: 12rem;
`;

const Content = styled.div`
  width: 100%;
  background-color: green;
  flex-basis: 75%;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Mazen Jamshed</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <SideBar />
      <Layout>
        <Content>
          <Hero />
          <Portfolio />
          <About />
          <Contact />
        </Content>
      </Layout>
    </>
  );
}
