import Head from 'next/head';
import SideBar from '../components/Sidebar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mazen Jamshed</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SideBar />
    </div>
  );
}
